version: '3.8'
services:
    jenkins:
        image: jenkins/jenkins:lts-jdk11
        container_name: jenkins
        ports:
            - 8080:8080
        volumes:
            - jenkins-data:/var/jenkins_home
            - npm-cache:/.npm
            - cypress-cache:/.cache
volumes:
    jenkins-data:
    npm-cache:
    cypress-cache:
